[package]
name = "kind-chatbot"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.11.23", features=["blocking","json"]}
rocket = {version = "0.5.0", features=["json"]}
openssl = { version = "0.10.59", features = ["vendored"] }
